name: Deploy Node.js app to Azure Web App - acad-assist

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install, build, test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip for deployment
        run: zip -r release.zip . -x ".git/*" "node_modules/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'acad-assist'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_4f6355d13d1144efa650f9fbae1cb0f7 }}
